# Generated by Django 6.0.3 on 2026-05-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_leaverequest_rejected_at_leaverequest_rejected_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
    ]
